Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Rafael Lima 
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2024
Var
   idade, anoA: inteiro
Inicio
      ESCREVA("Em que ano estamos: ")
      leia(anoA)
      escreva("Qual seu ano de nascimento: ")
      leia(idade)
      idade <- anoA - idade
      escreva("Você tem ", idade," anos de idade")
Fimalgoritmo