Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2024
Var
// Seção de Declarações das variáveis 
   n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("informe um número: ")
   leia(n)
   escreva("O Antecessor é: ", n - 1," o seu sucessor", n + 1)

Fimalgoritmo