Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2024
Var              \
   nome: cadeia
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe seu nome: ")
   leia(nome)
   
   escreva("O[á, ",nome,"!, Seja Bem Vindo")
Fimalgoritmo