Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2024
Var
   n: inteiro
   t: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe um número ")
   leia(n)
   
   t <- n / 3
   
   escreva("A terça parte é: ",t )
Fimalgoritmo