Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação]
// Professor   : Rafael Lima
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2024
Var
// Seção de Declarações das variáveis

 x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   x <- 1
   enquanto x < 20 faca
   se(x%2 = 0) entao
    escreva(x)
    fimse
    x <- x + 1
   fimenquanto

Fimalgoritmo