Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2024
Var
// Seção de Declarações das variáveis 

 x :inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 100
   enquanto x > 50 faca
    x <- x - 2
    escreval(x+1)
   fimenquanto

Fimalgoritmo