Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação]
// Professor   : Rafael Lima
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/08/2024
Var
   x, soma, num, num2: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   x <- 1
   repita
    escreva(x)
    x <- x + 1
   ate (x > 10)
Fimalgoritmo